// angular/todo-list/src/component/todo-list/todo-list.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'todo-list',
  template:`
  <div>
    <input [(ngModel)]="inputValue" />
    <button (click)="handleButtonClick()">提交</button>
  </div>
  <ul>
    <li *ngFor="let item of list; let index=index;">
      <todo-list-item
        [content]="item"
        [index]="index"
        (delete)="handleDelete($event)"></todo-list-item>
    </li>
  </ul>
`
})
export class TodoListComponent {

  public list: string[] = [];

  public inputValue: string = '';

  public handleButtonClick(): void {
    this.list.push(this.inputValue);
    this.inputValue = '';
  }

  public handleDelete(index: number) {
    this.list.splice(index, 1);
  }

}

// vue/es6/todo-list/src/components/todo-list/todo-list.vue
<template>
<div>
  <input v-model="inputValue" />
  <button @click="handleSubmit">提交</button>
  <ul>
    <todo-item v-for="(item, index) of list" :key="index"
               :content="item"
               :index="index"
               @delete="handleDelete">
    </todo-item>
  </ul>
</div>
</template>

<script>
import TodoItem from './todo-item';

export default {
  components: {'todo-item': TodoItem},
  data() {
    return {
      inputValue: '',
      list: []
    };
  },
  methods: {
    handleSubmit() {
      this.list.push(this.inputValue);
      this.inputValue = '';
    },
    handleDelete(index) {
      this.list.splice(index, 1);
    }
  }
};
</script>

<style>

</style>
